# Build script for Travis CI
#

# use xenial distro
dist: xenial

# no need to check for oracle's java
language: java
jdk: openjdk8

# speed up builds by caching maven local repository
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"

# as agreed in our SOP
branches:
  only:
  - master
  - development
  - release*
  - /^[vV]?\d+\.\d+\.\d+$/ # matches e.g., v1.2.3, 1.2.3, V1.2.3

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS

# dependencies for report generation (use cache to speed up builds)
install:
  - $HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh
# check if we need to add a license file for Vaadin charts
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then
                  echo "$VAADIN_CHARTS_LICENSE_CODE" > ~/.vaadin.charts.developer.license;
               fi;

# as agreed in our SOP, build everything (don't deploy, just try to 'mvn install' locally, which covers all phases)
script: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-SNAPSHOT versions:update-child-modules && mvn versions:commit &&
        mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml clean install
# upload code coverage report, generate maven site (javadocs, documentation, static code analysis, etc.)
after_success: 
- bash <(curl -s https://codecov.io/bash)

# upload to maven
deploy:
  # as agreed in our SOP, builds on development branch will deploy to our maven repository after validating
  # the artifact has a proper SNAPSHOT version
  # artifact will be installed in our testing instance if it is a .war file
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings .travis.settings.xml deploy
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
  # as agreed in our SOP, tagging a commit on the master branch will upload to our maven repository
  # after validating the artifact has a proper release version
  # artifact will be installed in our testing instance if it is a .war file
- skip_cleanup: true
  provider: script
  script: mvn build-helper:parse-version versions:set -DnewVersion=$TRAVIS_TAG -DprocessAllModules && mvn versions:commit &&
          mvn --quiet --activate-profiles !development-build,release-build --settings .travis.settings.xml deploy
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true

# activate our conda environment, generate maven site and upload reports to gh-pages branch
after_deploy:
  - echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc && conda activate qbic-docs-build
  - mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml site
  - ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages" "This commit was performed from travis-ci.com using a personal access key" "Build ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this build found at $TRAVIS_JOB_WEB_URL"

# change according to your needs, but we recommend to deactivate email notifications
# for now, we configured Travis to send a notification to the #travis-ci channel 
notifications:
  email:
    on_success: never
    on_failure: never
  slack: 
    on_success: never
    on_failure: always
    # edit the following section if you want to get slack notifications
    rooms:
      - secure: "***"