name: Sync qube project

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install qube
          run: pip install qube

        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
              token: '${{ secrets.JOHNNY_Q5_REPORTS_TOKEN  }}'
          name: Check out source-code repository

        - uses: oleksiyrudenko/gha-git-credentials@v2
          with:
              name: 'JohnnyQ5'
              email: 'support@qbic.zendesk.com'
              actor: 'JohnnyQ5'
              token: '{% raw %}${{ secrets.JOHNNY_Q5_REPORTS_TOKEN}}{% endraw %}'

        - name: Sync project
          run: qube sync . {% raw %}${{ secrets.JOHNNY_Q5_REPORTS_TOKEN  }}{% endraw %} JohnnyQ5
